name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install Server
        run: |
          cd server
          npm install

      - name: Run Server
        env:
          MONGO_URI: mongodb://localhost:27017/testdb
        run: |
          cd server
          node index.js &
          sleep 5

      # Frontend
      - name: Install Client
        run: |
          cd client
          npm install

      - name: Build Client
        run: |
          cd client
          npm run build